const sayHi = require('./utils')
const names = require('./names')
const expo = require('./3-expo')
require('./mind-grenade')
//console.log(expo)
//console.log(names)
//sayHi('susan')
//sayHi(names.john)
//sayHi(names.peter)
